# Generated by Django 3.1.6 on 2021-02-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cover',
            field=models.FileField(default=1, upload_to='cover/'),
            preserve_default=False,
        ),
    ]
