# Generated by Django 3.1.6 on 2021-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storeopening',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
